spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sketchbook?characterEncoding=UTF-8&serverTimezone=UTC
    username: ader
    password: 1234

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true